### ISSUE TITLE
호텔 검색 REST-API

### ISSUE THREAD

**Issue by JoisFe** [JoisFe/MSA-SpringBoot#1]
# Issue: 
- 호텔 검색 REST-API 

<br>

### Description
- 간단하게 호텔 id로 호텔을 검색하는 REST-API 구현
<br>

### Todo
- [x] 호텔 id로 호텔 검색 REST-API 설계
- [x] 호텔 도메인 구현
- [x] 위 기능 Controller 메서드 구현
- [x] 위 기능 Service 구현
<br>

### Etc
- Swagger 혹은 Postman으로 요청에 대한 결과 확인해보기
