### ISSUE TITLE
데이터 검증과 에러 처리(호텔 객실 예약 REST-API)

### ISSUE THREAD

**Issue by JoisFe** [JoisFe/MSA-SpringBoot#11]
# Issue: 
- 데이터 검증과 에러 처리(호텔 객실 예약 REST-API)

<br>

### Description
- 클라이언트의 요청을 검증
- 검증 결과 잘못된 경우의 에러 처리
<br>

### Todo
- [x] JSR-303을 이용한 데이터 검증
- [x] @Valid 어노테이션을 이용한 자바 빈 객체 마킹
- [x] Validator 인터페이스를 이용한 검증
- [x] BindingResult로 검증 에러 핸들링
- [x] 호텔 객실 예약 REST-API 기능 구현
- [x] @ControllerAdvice, @ExceptionHandler를 이용한 예외 처리
<br>

### Etc
- JSR-303에서 제공하는 어노테이션은 하나의 속성에 여러 어노테이션 조합해 검증하는 방식으로 검증 조건이 복잡해지면 검증이 쉽지 않음
- Validator를 이용하여 검증하여 위 단점을 해결해보자.
