### ISSUE TITLE
호텔 객실 검색, 삭제 API

### ISSUE THREAD

**Issue by JoisFe** [JoisFe/MSA-SpringBoot#3]
# Issue: 
- 호텔 객실 검색, 삭제 API

<br>

### Description
- 호텔 룸 검색 API를 만들어보면서  @PathVariable, @RequestParam 어노테이션과 @GetMapping, @DeleteMapping 어노테이션에 대해서도 알아볼 것
- @DateTimeFormat에 대해 알아보자
- Json 타입으로 직렬화를 하기 위한 방법에 대해 알아보자
<br>

### Todo
- [x] 호털 객실 검색 기능 구현
- [x] 호텔 객실 삭제 기능 구현
- [x] 날짜, 시간을 원하는 타입으로 포맷팅 하기
- [x] 응답 객체 JSON 타입 직렬화 위한 Serializer 구현
<br>

### Etc
- HTTP method GET, DELTE에 특징에 대해 알아보자
- 날짜, 시간 포맷팅 방식 알아보자
- JSON 직렬화에 대해 알아보자
