### ISSUE TITLE
호텔 객실 예약 정보 REST-API

### ISSUE THREAD

**Issue by JoisFe** [JoisFe/MSA-SpringBoot#7]
# Issue: 
- 호텔 객실 예약 정보 REST-API

<br>

### Description
- 호텔 객실 예약 정보 Controller 구현
- ResponseEntity 클래스를 이용한 응답처리
- Pageable, Sort를 이용한 Paging
<br>

### Todo
- [x] 호텔 객실 예약 정보 API 구현
- [x] ResponseEntity 클래스를 이용하여 요청에 대해 올바른 응답 반환
- [x] Pageable, Sort를 이용하여 일정한 크기의 데이터를 정렬하여 가져오기
<br>
